giveauthnet.settings:
  type: config_object
  label: Give Authorized Settings
  mapping:
    api_login_id:
      type: text
      label: Authorize.net API login ID
    transaction_key:
      type: text
      label: Authorize.set Transaction key
    cancel_message:
      type: text
      label: Message displayed with the user cancel the donation.
    thanks_message:
      type: text
      label: Message displayed after the user donation.